import type { ReviewItem } from "./schema";

// Real Google reviews for Agra Tour Guides — verified April 2026.
// Source: Google Business Profile (5.0★ / 81 reviews).
// `country` is best-effort inferred from reviewer name + Local Guide locale where reasonable;
// leave undefined when unsure. `datePublished` uses month/year — exact day not always shown by Google.

export const REAL_REVIEWS: ReviewItem[] = [
  {
    author: "Klára Holubová",
    country: "Czech Republic",
    rating: 5,
    text: "Pawan was very attentive and extremely knowledgeable about the Taj Mahal and its history. He also took amazing photos for me. Highly recommended.",
    datePublished: "2026-02-15",
  },
  {
    author: "Manpreet Kaur Saran",
    country: "India",
    rating: 5,
    text: "We had an amazing experience with our guide at the Taj Mahal in Agra. From the moment we arrived, he was professional, knowledgeable, and very friendly. He explained the history of the beautiful Taj Mahal in such an interesting and detailed way that it made the visit even more special.",
    datePublished: "2026-03-10",
  },
  {
    author: "Karin Stehr",
    country: "Germany",
    rating: 5,
    text: "Today we have visited Taj Mahal guided by Pawan. We are very happy with his recommendation to start early at 7 o'clock. It was the perfect light situation and not so many people. Pawan was an excellent guide and gave us many interesting historical and architectural details.",
    datePublished: "2026-02-20",
  },
  {
    author: "Anusha Cooshnea",
    country: "Mauritius",
    rating: 5,
    text: "Pawan was an amazing guide. I highly recommend him for your visit in Taj Mahal. Well done and thank you for everything.",
    datePublished: "2026-03-05",
  },
  {
    author: "David Price",
    country: "United Kingdom",
    rating: 5,
    text: "We only had a short time to be in Agra. Pawan helped make the trip so memorable. He took his time to explain the history and wonder of the Taj Mahal. He took amazing pictures and showed us around to good shops. I will be sending all my family and friends to see Pawan when they come to Agra!",
    datePublished: "2026-02-12",
  },
  {
    author: "Ivy Chtu",
    country: "Singapore",
    rating: 5,
    text: "Great tour guide explained every monument in great detail. Also takes incredible photos.",
    datePublished: "2026-02-25",
  },
  {
    author: "Priyam Bortamuli",
    country: "India",
    rating: 5,
    text: "We had a great experience with Mr Pawan Agarwal — our Guide at the Taj Mahal. He not only made our trip to majestic Taj Mahal cherishable with his knowledge sharing, but also enhanced the experience with his amazing photography skills. We recommend Mr Pawan as the best guide!",
    datePublished: "2025-12-18",
  },
  {
    author: "Harsha Upadhyay",
    country: "United States",
    rating: 5,
    text: "Pawan was our guide at Agra and helped us get to see the famous Taj Mahal! We started our correspondence through WhatsApp to discuss the logistics. He was a great communicator with attention to detail. On the day of our tour, he came to meet us prepared and on time.",
    datePublished: "2024-04-20",
  },
  {
    author: "Donson Rebello",
    country: "India",
    rating: 5,
    text: "We met Pawan from Agra Tour Guide during our visit to the Taj Mahal, and he made the whole experience so much better. He explained the history and craftsmanship of the monument in a way that was engaging and easy to connect with — not just dates and names but stories.",
    datePublished: "2025-10-22",
  },
  {
    author: "Divya Kumari",
    country: "India",
    rating: 5,
    text: "He provided fascinating historical details, lesser-known facts, and even explained the intricate architectural designs. His storytelling brought the history of the Taj Mahal to life. He helped us take the best photos, guided us through the crowds smoothly, and even recommended great local restaurants nearby.",
    datePublished: "2025-04-10",
  },
  {
    author: "Sameer Khairkar",
    country: "India",
    rating: 5,
    text: "Pawan was absolutely brilliant! From navigating the streets to get us quickly into the Taj, to getting us the best pictures — it's an Insta world we live in. To sharing the knowledge of the Taj, everything was great and would definitely recommend!",
    datePublished: "2025-05-15",
  },
  {
    author: "Youssef Demitri",
    country: "Egypt",
    rating: 5,
    text: "Pawan was great guide, knowledgeable, friendly and knows all the right angles for a good photoshoot at the Taj.",
    datePublished: "2025-10-05",
  },
  {
    author: "Nasser Al-Shaqsi",
    country: "Oman",
    rating: 5,
    text: "Pawan is very knowledgeable and friendly. He was aware about Taj Mahal history. Moreover he is good photographer.",
    datePublished: "2025-04-28",
  },
  {
    author: "Faizan Ahmed",
    country: "United Arab Emirates",
    rating: 5,
    text: "Perfect tour. Was very informative and well taken care of. Amazing pictures clicked throughout.",
    datePublished: "2026-01-30",
  },
  {
    author: "Mohd Nasir Abd Rahman",
    country: "Malaysia",
    rating: 5,
    text: "All good. Helpful and satisfactory. Pawan was our guide. Recommended if you want to avoid the hassle of touts and sellers along the way.",
    datePublished: "2025-09-15",
  },
  {
    author: "Raj Singh",
    country: "United States",
    rating: 5,
    text: "Pawan Agarwal was excellent Tour Guide while we visited Taj Mahal in Agra. We enjoyed his company while getting educated about the history of Taj Mahal and the craft work being done in the City of Agra still to this date. We enjoyed the demonstration of the marble inlay work and hand made carpets at the nearby handicraft factories.",
    datePublished: "2025-06-12",
  },
  {
    author: "Lorenzo Valentino",
    country: "Italy",
    rating: 5,
    text: "Very good guy, friendly and speaks good English.",
    datePublished: "2026-01-20",
  },
  {
    author: "Reeti Bangia",
    country: "India",
    rating: 5,
    text: "Pavan was very helpful and knowledgeable. And knew the best spots for the photos.",
    datePublished: "2026-02-08",
  },
  {
    author: "Nandini Jain",
    country: "India",
    rating: 5,
    text: "Wonderful experience! Mr. Pawan was our guide. He not only gave a wonderful tour but also clicked beautiful pictures. He was very polite and more of that a good human being.",
    datePublished: "2025-05-22",
  },
  {
    author: "Cryonet",
    country: "United Kingdom",
    rating: 5,
    text: "The best guide there is, period. Look elsewhere if you want a subpar experience because you've found the best, he's here! Even took beautiful pictures with our phone free of charge!",
    datePublished: "2025-07-08",
  },
  {
    author: "Sahaay Foundation",
    country: "India",
    rating: 5,
    text: "We loved the experience with our tour guide Pavan. Very knowledgeable and exceptionally patient with the tourists. I would recommend him to any tourist planning to visit Agra Taj Mahal.",
    datePublished: "2025-08-18",
  },
  {
    author: "Neha M Noel",
    country: "India",
    rating: 5,
    text: "Our guide Pawan made this a wonderful and unforgettable experience, definitely would recommend!",
    datePublished: "2026-01-25",
  },
  {
    author: "Prashant Singh",
    country: "India",
    rating: 5,
    text: "Pawan ji was amazing and very patient with all of us. He took time to explain everything at length. Highly recommended.",
    datePublished: "2025-11-30",
  },
  {
    author: "Revilo",
    country: "United States",
    rating: 5,
    text: "A tour guide is a must for anyone visiting the Taj Mahal. My guide was incredibly knowledgeable, sharing fascinating details about the history, architecture, and love story behind the monument. He made the experience more meaningful by adding personal anecdotes.",
    datePublished: "2025-04-15",
  },
  {
    author: "Manu Seoane",
    country: "Spain",
    rating: 5,
    text: "Amazing guide for Taj Mahal. He helped us with everything and made our experience more enjoyable.",
    datePublished: "2025-09-22",
  },
  {
    author: "Natascha Assies",
    country: "Netherlands",
    rating: 5,
    text: "Very kind tour guide, we had a perfect day!",
    datePublished: "2026-01-18",
  },
  {
    author: "Kannan Alford",
    country: "United States",
    rating: 5,
    text: "Pawan was an excellent tour guide. We had a great, stress free experience at the Taj Mahal.",
    datePublished: "2025-08-25",
  },
  {
    author: "Maxym Sutton",
    country: "United Kingdom",
    rating: 5,
    text: "Pawan was the best! We had a great time with him and he helped us around the Taj Mahal, took wonderful photos for us, and helped us get great deals on items in the shops.",
    datePublished: "2025-05-30",
  },
  {
    author: "Suriya Rajaram",
    country: "India",
    rating: 5,
    text: "Pawan is kind and informative being a guide. He was very helpful and friendly.",
    datePublished: "2025-12-08",
  },
  {
    author: "Anand Reddy",
    country: "India",
    rating: 5,
    text: "Good tour of Taj Mahal. Very informative.",
    datePublished: "2026-01-30",
  },
  {
    author: "Mike Cordery",
    country: "Australia",
    rating: 5,
    text: "Pawan is more than just a Tour Guide. He is a creative photographer, a funny storyteller, a charming, friendly host and a knowledgeable historian of the Taj Mahal. In addition he speaks fluent Japanese! We recommend his services without hesitation.",
    datePublished: "2025-03-15",
  },
  {
    author: "Stephan Riederer",
    country: "Germany",
    rating: 5,
    text: "Highly recommend Pawan ji. He's kind, knowledgeable and the best photographer.",
    datePublished: "2025-12-15",
  },
  {
    author: "Raja Sudhan",
    country: "India",
    rating: 5,
    text: "Was guided by Mr. Pawan at Taj Mahal. He did a phenomenal job of making our experience great. He explained the architecture and history in detail and was able to do it in English as well. He suggested photo spots and became our personal photographer for the morning.",
    datePublished: "2024-04-10",
  },
  {
    author: "Kamal Malhi",
    country: "Canada",
    rating: 5,
    text: "The tour was covered in detail with wonderful suggestions for photography angles as well as historical details. Pawan Aggarwal ji is an experienced guide that I highly recommend.",
    datePublished: "2025-04-08",
  },
  {
    author: "Linus Kabutha",
    country: "Kenya",
    rating: 5,
    text: "Pawan was exceptional! We had a good time with him. He is knowledgeable and his English was spot on. I would not hesitate to recommend him. All the way from Kenya!",
    datePublished: "2025-03-20",
  },
  {
    author: "Abby Augustine",
    country: "United States",
    rating: 5,
    text: "Pavan was an excellent guide and photographer! I'd highly recommend requesting him as he will be very wonderful to work with. Our time was limited and he accommodated our wishes perfectly!",
    datePublished: "2025-04-25",
  },
  {
    author: "Keith Irvine",
    country: "Australia",
    rating: 5,
    text: "I highly recommend Pawan for tours. He is a very friendly person with lots of knowledge on the Taj Mahal. He also showed the fort and the other places of interest in Agra.",
    datePublished: "2024-03-18",
  },
  {
    author: "Erlend Scheers",
    country: "Belgium",
    rating: 5,
    text: "Great visit, thanks to the guide who was very knowledgeable and shared a lot of interesting anecdotes. I can recommend him for anyone who likes to visit Taj Mahal.",
    datePublished: "2025-04-12",
  },
  {
    author: "Sophia Jalil",
    country: "United Kingdom",
    rating: 5,
    text: "Pawan is extremely knowledgeable and passionate about Agra. He showed us around and gave us so much information. Pawan made our trip to Agra a memorable one. Thank you.",
    datePublished: "2024-02-15",
  },
  {
    author: "James O'Brien",
    country: "Ireland",
    rating: 5,
    text: "Pawan was amazing. Would highly recommend! Incredibly knowledgeable, friendly and kind. Had a wonderful experience, thank you again for a great day.",
    datePublished: "2025-05-18",
  },
  {
    author: "Vince Leone",
    country: "Italy",
    rating: 5,
    text: "Thank you Pawan for your amazing tours and local knowledge. We learnt so much and had a lot of fun!",
    datePublished: "2024-03-10",
  },
  {
    author: "Niresh Madhanpall",
    country: "South Africa",
    rating: 5,
    text: "Very polite, accommodating and knowledgeable tour guide. Made our experience very pleasant and memorable.",
    datePublished: "2024-04-08",
  },
  {
    author: "Wiaes Honardoust",
    country: "Iran",
    rating: 5,
    text: "Great tour guide in Agra Taj Mahal.",
    datePublished: "2025-03-22",
  },
  {
    author: "Sannu Raja",
    country: "India",
    rating: 5,
    text: "Great guide and photographer, highly recommend.",
    datePublished: "2025-05-08",
  },
  {
    author: "Gabriela Swain",
    country: "United Kingdom",
    rating: 5,
    text: "Our Agra Tour Guide was super helpful during our visit to Taj Mahal. He ensured a smooth queuing process and arranged a good photographer. He was also very knowledgeable and nice in general. I can highly recommend to book a guide!",
    datePublished: "2026-04-15",
  },
  {
    author: "Ami Patel",
    country: "United States",
    rating: 5,
    text: "Pawan took my family and I around Taj Mahal today. Great English speaking guide with brilliant knowledge and incredible photography skills! He was fast and efficient with taking photos so kids didn't get frustrated. 100% recommend Pawan.",
    datePublished: "2026-03-22",
  },
  {
    author: "Natasha Chauhan",
    country: "United Kingdom",
    rating: 5,
    text: "We had a fantastic tour yesterday with our guide Pawan. His knowledge of the Taj Mahal was amazing. We enjoyed so much and will be recommending him to our friend and family. He also took great pictures and was really nice.",
    datePublished: "2026-03-18",
  },
  {
    author: "Siham Kamal",
    country: "France",
    rating: 5,
    text: "Wonderful experience with our guide Pawan; he was attentive and provided helpful advice throughout our visit! I highly recommend him.",
    datePublished: "2025-08-30",
  },
];

export const TOTAL_REVIEW_COUNT = 81;
